name: Pruebas Automatizadas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v3

      - name: Configurar JDK 17 JAVA
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permisos de ejecución a gradlew
        run: chmod +x ./gradlew

      - name: Ejecutar pruebas
        run: ./gradlew test